services:
  bambu-api-server:
    container_name: bambu-api-server
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./configs:/bambu-server/configs
    ports:
      - "5123:5123"